apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHpzemZhZWd2
  CLOUDINARY_KEY: NTMyMjgzNjEzNTk5Mjg0
  CLOUDINARY_SECRET: cU4wOVFsUUhNa25kYmRva1FEZDYwNEEzVmFj
  MAPBOX_TOKEN: cGsueWVKMWlqb2lhR0Z5YzJoaGJHdGtZVEV5TXlJc0ltRWlPaUpqYlc1aE9IUmxjMlV3WkdGcE1tOXlObXRrT1hGMWFYVnJJbjAuUTdQajF4MGtyZjJvd1NkdmwyaG4tQQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjEyM0BjbHVzdGVyMC5kZGpwa2hmLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
